### ISSUE TITLE
Is this a fork of openapi-spec-validator?

### ISSUE THREAD

**Issue by jiss2891** [p1c2u/openapi-schema-validator#7]
Also, you might consider enabling the "Discussions" tab to increment interaction with the project.

**Comment by jgod** [comment]
I find the relationship between the projects a little confusing

**Comment by tsingh2k15** [comment]
I have a similar question as @jiss2891 
I am confused on which one should I use `openapi-schema-validator` or `openapi-spec-validator` ?

**Comment by p1c2u** [comment]
In short, no, It's not a fork.

[OpenAPI schema](https://swagger.io/specification/#schema-object) is part of [OpenAPI Specification](https://swagger.io/specification/). That's why `openapi-spec-validator` uses `openapi-schema-validator` to validate default values in the specification against it's schema.

Maybe we should add the information about the difference in the README
